FirstCommitForChecking
DenisKachan/Diploma_Project pull request #1
Opened 2022-07-26 00:00 UTC by DenisKachan

2022-07-27 17:00 UTC, VladimirVolkovD requested changes

2022-07-27 17:00 UTC, VladimirVolkovVD commented on src/test/java/UI/BrowserConfig/SelenideConfiguration.java
> +        Configuration.headless = false;
переменные в проперти файл, если уже начал

2022-07-27 17:00 UTC, VladimirVolkovVD commented on src/test/java/UI/Utils/TestConstants.java
> +    String VALID_PASSWORD = "proEVOlution20jomaQ";
Базовые переменные лучше в проперти (email, password)

2022-07-27 17:00 UTC, VladimirVolkovVD commented on src/test/java/UI/Utils/TestConstants.java
> +    String INVALID_PASSWORD = "adfdfsadf";
invalid data сгенерировать, нет смысла их хранить

2022-07-27 17:00 UTC, VladimirVolkovVD commented on src/test/java/UI/Pages/CreateNewTestRunPage.java
> +    public ListOfTestRunsPage successfulTestRunCreation() {
мараметр имени для тест рана лучше передать как параметр, и если он null взять рандомный валидный

2022-07-27 17:00 UTC, VladimirVolkovVD commented on src/test/java/UI/Pages/CreateNewTestRunPage.java
> +        saveRunButton.click();
как узнать имя созданного тайтла? сли необходимо вернуть его из метода

2022-07-27 17:00 UTC, VladimirVolkovVD commented on src/test/java/UI/Pages/LoginPage.java
> +        login(INVALID_EMAIL, INVALID_PASSWORD);
не валидные данные можно сгенирировать

2022-07-27 17:00 UTC, VladimirVolkovVD commented on src/test/java/UI/Steps/CaseSteps.java
> +        repositoryPage.testCaseTitle.should(Condition.have(Condition.text(TEST_CASE_TITLE)));
почем проверка тут и какой тайтл пмы проверяем? откуда мы его указываем?

2022-07-27 17:01 UTC, VladimirVolkovD commented
Тестовые данные зашиты в логику пейджей, нет возможности передавать их с уровня тестов

2022-08-01 12:18 UTC, VladimirVolkovD approved these changes

2022-08-01 12:36 UTC, merged